### ISSUE TITLE
How to get all rows from table using sql_orm ?

### ISSUE THREAD

**Issue by adibro500** [matt-42/lithium#11]
How to get all rows from table using sql_orm ? Please guide me here
`
error: 'struct li::mysql_result<li::mysql_functions_blocking>' has no member named 'map'
   29 | connection("Select id,time from items_table;").map([&] (std::string id, std::string time) {
`

Getting the above error
Thanks,
adibro500

**Comment by matt-42** [comment]
You have a forall method for this:

see this example:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C%2B%2B/lithium/lithium.cc#L189

Matthieu Garrigues

**Comment by adibro500** [comment]
Not working with sql commands.

`con("select name, age from users;").map([] (std::string name, int age) {
  std::cout << name << ":" << age << std::endl;
});`

This example not working.

**Comment by matt-42** [comment]
Are you using mysql, postgres or sqlite ?

Matthieu Garrigues

**Comment by adibro500** [comment]
using mysql

**Comment by adibro500** [comment]
Also I am getting CORS error

**Comment by adibro500** [comment]
the `Access-Control-Allow-Origin` working only in get apis

**Comment by matt-42** [comment]
Use the prepared statement api for the map method:

`connection.prepare("Select id,time from items_table;").map([...])`

I'll add an issue to have the map method on the non prepared mysql queries.

**Comment by matt-42** [comment]
CORS error mean you use different hostname or port to serve the API.
You should use the same otherwise the browser will block the request.


Matthieu Garrigues

**Comment by adibro500** [comment]
Getting this error:
`
error: 'struct li::mysql_statement<li::mysql_functions_blocking>' has no member named 'map'
`

**Comment by matt-42** [comment]
Sorry I forgot to call the prepared statement, use this instead:
`
connection.prepare("Select id,time from items_table;")().map([...])`

**Comment by adibro500** [comment]
getting this error : 

`
/usr/local/include/c++/9.3.0/tuple:1277:29: error: incomplete type 'std::tuple_size<main()::<lambda(li::http_request&, li::http_response&)>::<lambda(std::string&, std::string&, std::string, std::string&, std::string&)> >' used in nested name specifier
 1277 |     inline constexpr size_t tuple_size_v = tuple_size<_Tp>::value;
      |                             ^~~~~~~~~~~~
`

**Comment by matt-42** [comment]
can you share the code that generated this error ?

**Comment by adibro500** [comment]
This code caused the error:

`db.connect().prepare("Select id,post from post_items;").map([&](std::string& id, std::string& post) {

});`
what i am doing wrong ?

**Comment by matt-42** [comment]
Do you still have this compilation  error ? I've added a test and it seems to compile and work fine on my computer. (But it fails on travis, still have to find why...):
https://github.com/matt-42/lithium/blob/master/libraries/sql/tests/mysql.cc#L53

**Comment by adibro500** [comment]
which compiler and compiler version you are using ?

**Comment by adibro500** [comment]
I am using gcc version 9.3.0

**Comment by matt-42** [comment]
I also have gcc 9.3.0, can you share a simple c++ pease of code that would allow me to reproduce the error ?

**Comment by adibro500** [comment]
db.connect().prepare("Select id,post from post_items;")().map([&](std::string id, std::string post) {

});

**Comment by matt-42** [comment]
this code is right, the error must come from somewhere else. If you want me to help more please share a c++ file that I can compile myself.

**Comment by matt-42** [comment]
Also note that on master the non prepared query API is finished.
You can now use:
```
db.connect()("Select id,post from post_items;").map([&](std::string id, std::string post) {

});
```

**Comment by matt-42** [comment]
Did you succeed ? can we close this issue ?

**Comment by adibro500** [comment]
Yes working
