### ISSUE TITLE
Getting the error for building with postgresql

### ISSUE THREAD

**Issue by adibro500** [matt-42/lithium#15]
`
/usr/local/include/li/sql/pgsql.hh:19:10: fatal error: libpq-fe.h: No such file or directory
   19 | #include "libpq-fe.h"
      |          ^~~~~~~~~~~~
`

Getting this error when compiling the pgsql database connection

Why is it pointing to current directory ?

**Comment by matt-42** [comment]
What distribution are you using ?

**Comment by matt-42** [comment]
If ubuntu you need these packages:  postgresql-server-dev-all libpq-dev
