### ISSUE TITLE
Unreachable code in mysql wrapper?

### ISSUE THREAD

**Issue by audaki** [matt-42/lithium#16]
Hello Matthieu,

we found your library for a project where we needed a MySQL connection and loving it so far. While looking at the code I noticed following code line: https://github.com/matt-42/lithium/blob/master/libraries/sql/sql/mysql.hh#L63

Isn't this unreachable code and maybe a memory leak or am I missing some macro magic? :D

kind regards, Kira

**Comment by matt-42** [comment]
Fixed!  thanks for the report.
