### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by CatsMum** [matt-42/lithium#2]
cd /home/nicole/software/cpp/lithium-master/libraries/http_backend/benchmarks && /bin/c++  -DBOOST_ALL_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -I/home/nicole/software/cpp/lithium-master/include -I/usr/include/mysql -I/opt/pgsql-11/include/server -isystem /include  -std=gnu++17 -o CMakeFiles/bench.dir/bench.cc.o -c /home/nicole/software/cpp/lithium-master/libraries/http_backend/benchmarks/bench.cc
/home/nicole/software/cpp/lithium-master/libraries/http_backend/benchmarks/bench.cc: In function ‘float tune_n_sql_connections(std::string, int, int)’:
/home/nicole/software/cpp/lithium-master/libraries/http_backend/benchmarks/bench.cc:192:18: error: invalid initialization of reference of type ‘const std::vector<int>&’ from expression of type ‘int’
  192 |   http_benchmark(512, 1, 1000, port, http_req);
      |                  ^~~
In file included from /home/nicole/software/cpp/lithium-master/include/li/http_backend/http_backend.hh:24,
                 from /home/nicole/software/cpp/lithium-master/libraries/http_backend/benchmarks/bench.cc:1:
/home/nicole/software/cpp/lithium-master/include/li/http_backend/http_benchmark.hh:111:46: note: in passing argument 1 of ‘float li::http_benchmark(const std::vector<int>&, int, int, std::string_view)’
  111 | float http_benchmark(const std::vector<int>& sockets, int NTHREADS, int duration_in_ms,
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/nicole/software/cpp/lithium-master/libraries/http_backend/benchmarks/bench.cc:201:38: error: invalid initialization of reference of type ‘const std::vector<int>&’ from expression of type ‘int’
  201 |     float req_per_s = http_benchmark(512, 1, 400, port, http_req);
      |                                      ^~~
In file included from /home/nicole/software/cpp/lithium-master/include/li/http_backend/http_backend.hh:24,
                 from /home/nicole/software/cpp/lithium-master/libraries/http_backend/benchmarks/bench.cc:1:
/home/nicole/software/cpp/lithium-master/include/li/http_backend/http_benchmark.hh:111:46: note: in passing argument 1 of ‘float li::http_benchmark(const std::vector<int>&, int, int, std::string_view)’
  111 | float http_benchmark(const std::vector<int>& sockets, int NTHREADS, int duration_in_ms,
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
make[2]: *** [libraries/http_backend/benchmarks/CMakeFiles/bench.dir/build.make:66: libraries/http_backend/benchmarks/CMakeFiles/bench.dir/bench.cc.o] Error 1

**Comment by matt-42** [comment]
Fixed. Thanks for the report.
