### ISSUE TITLE
How do I get IP address of client?

### ISSUE THREAD

**Issue by sptrakesh** [matt-42/lithium#20]
Is there a way to determine the IP address of the client connected to the http backend?  I am aware this can be spoofed, or masked behind proxy etc., but I am trying to build some geographical analytics around visitor data.

I do look for `x-real-ip` or `x-forwarded-for` headers, but want a fallback if not available via header.

**Comment by matt-42** [comment]
There is no way for now. I'm adding it.

**Comment by matt-42** [comment]
With 2cadfd837d8dc6e23a39e2c04d3213543df32bb3  , you can call request.ip_address() to get a string representation of the ip adress.
