### ISSUE TITLE
Symbols generator built, but not installed

### ISSUE THREAD

**Issue by c-cesar** [matt-42/lithium#22]
Installing the framework via CMake, the symbol generator utility is built, under `lithium/build/libraries/symbols/li_symbol_generator`, but the target not installed.
I tried to call the custom target with `make symbol_generation` but without success.

**Comment by matt-42** [comment]
Fix in 3661bdc84174bf9f676fe88c4486f5df2eeb69ff  . Thanks for the report! I've also added more explaination in the main readme: https://github.com/matt-42/lithium#getting-started-or-setting-up-automatic-symbol-generation
