### ISSUE TITLE
Add a conan package

### ISSUE THREAD

**Issue by matt-42** [matt-42/lithium#27]

**Comment by BlueSolei** [comment]
I would love to take a shoot at this

**Comment by matt-42** [comment]
You're welcome ! 

Let me do some fixes to the CmakeList.txt first. I'll let you know when I'm done.

**Comment by matt-42** [comment]
It's ok @BlueSolei . Now `make install` install the single headers and the symbol generation, that's all we need to put in the conan package. Don't hesitate if you have question when adding the conan package.

**Comment by matt-42** [comment]
Once you're done, could you also add a conan section in the installation readme ?  https://github.com/matt-42/lithium/blob/master/INSTALL.md

**Comment by BlueSolei** [comment]
Sure.
I will work on it this weekend.

**Comment by matt-42** [comment]
@BlueSolei are you still on this ? Or you need somebody else to take the lead ?

**Comment by BlueSolei** [comment]
I think I would pass :-(
Sorry.

**Comment by matt-42** [comment]
Ok no problem. I'll do it.
