### ISSUE TITLE
List of websites/APIs using lithium

### ISSUE THREAD

**Issue by METACEO** [matt-42/lithium#33]
Hi @matt-42, if there are existing websites or APIs using lithium (demos, examples, production apps, etc.) could the README include a list of these? Any that are open source would especially be great, too!

**Comment by matt-42** [comment]
Yes I can start one. But the framework is pretty young so the list will be pretty short at first ☺️

**Comment by matt-42** [comment]
I added a section "Projects using Lithium' in the main readme. I'm aware of only one project for now.
