### ISSUE TITLE
VC++2019 compilation error

### ISSUE THREAD

**Issue by stullemitbrot** [matt-42/lithium#4]
Trying to compile I get the folloing error message: 
...lithium\single_headers/lithium_http_client.hh(591,87): error C3543: 'metamap<M1,Ms...>::Ms::_iod_value_type &&': does not contain a parameter pack
...lithium\single_headers/lithium_http_client.hh(603): message : see reference to class template instantiation 'li::metamap<M1,Ms...>' being compiled
It's the same error with the single header libs and the lithium package cmake build.
Help highly appreciated.
Thank You! Reinhard

**Comment by matt-42** [comment]
I'll drop windows support since the compiler still has bugs. Sorry for that. I'll update the documentation
