### ISSUE TITLE
Performance Benchmarks?

### ISSUE THREAD

**Issue by Zenahr** [matt-42/lithium#40]
Are there any performance benchmarks for lithium? Something like this would be cool: https://www.grandmetric.com/2020/08/10/python-rest-frameworks-performance-comparison/

**Comment by matt-42** [comment]
Lithium is ranked #1 on the techempower benchmark including hundreds of frameworks:  https://www.techempower.com/benchmarks/#section=test&runid=3097dbae-5228-454c-ba2e-2055d3982790&hw=ph&test=composite&a=2 

It you would like to see lithium in any other benchmark open for a new C++ competitor please share it here.

**Comment by Zenahr** [comment]
@matt-42 I wasn't able to find that benchmark myself. Would be awesome to have it being added to the readme.

**Comment by matt-42** [comment]
Just added it. Thanks @Zenahr  for the feedback.
