### ISSUE TITLE
DB Connection Pooling Support

### ISSUE THREAD

**Issue by aviezab** [matt-42/lithium#6]
Hey Matt, I am really interested to use lithium as back end in our stack. Could You confirm that the DB function You provided is already using DB connection pooling?

`auto connection = database.connect();`

**Comment by matt-42** [comment]
Yes! The database object manages a pool.

**Comment by aviezab** [comment]
Hi @matt-42 Which boost version do You use?

**Comment by matt-42** [comment]
I have 1.72 installed but it should work with earlier versions as well.
