### ISSUE TITLE
Connection not closing

### ISSUE THREAD

**Issue by ZinoviL** [matt-42/lithium#69]
I'm trying to test Lithium using ab (Apache HTTP server benchmarking tool) and connection not closing.
Code:
![Screenshot from 2021-04-01 15-20-50](https://user-images.githubusercontent.com/9405816/113280546-de5dc300-92fd-11eb-9dd8-1a91bed55c97.png)
Cmake:
![Screenshot from 2021-04-01 15-21-19](https://user-images.githubusercontent.com/9405816/113280640-fd5c5500-92fd-11eb-8c0a-777d982d5112.png)
Result:
![Screenshot from 2021-04-01 15-19-26](https://user-images.githubusercontent.com/9405816/113280471-c5551200-92fd-11eb-8197-b09e96500b09.png)

**Comment by matt-42** [comment]
thanks for the report, I´ll investigate this next week when I´ll be completely free to work on lithium

**Comment by matt-42** [comment]
Hi @ZinoviL ,

Lithium has no fallback for HTTP 1.0 . Which is why the connection stays open (the default for HTTP 1.1). Do you really need support of HTTP 1.0 ?  I you need a benchmarking tool supporting HTTP 1.1 I recommand wrk: https://github.com/wg/wrk

**Comment by ZinoviL** [comment]
@matt-42 Yeah, i know about wrk, but i didn't find any info about http1 in your docs. But thanks for explanation.

**Comment by matt-42** [comment]
I'll add a note on this in the docs.
