### ISSUE TITLE
Memory leak in json_parser/make_json_error 

### ISSUE THREAD

**Issue by vpiscitello** [matt-42/lithium#82]
Hey, I noticed a memory leak when a buffer containing malformed JSON is decoded. It appears that the make_json_error method allocates a new std::ostringstream that is never deleted. Seems like it would be an easy fix to use std::unique_ptr instead of a raw pointer for the error_stream.

**Comment by MohammadArik** [comment]
I am having trouble in installing.. Anyone can help?
